include: package:very_good_analysis/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
  exclude:
    - flutter/**
    - lib/api/*.dart


linter:
  rules:
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    sort_constructors_first: false
    public_member_api_docs: false
    library_private_types_in_public_api: false
    no_default_cases: false
    omit_local_variable_types: false