name: dismissible_page
description: Creates page that is dismissed by swipe gestures, with Hero style animations, Inspired by Facebook, Instagram stories.
version: 1.0.0
homepage: https://github.com/Tkko/Flutter_dismissible_page
repository: https://github.com/Tkko/Flutter_dismissible_page
issue_tracker: https://github.com/Tkko/Flutter_dismissible_page/issues
screenshots:
  - description: 'Dismissible page demo'
    path: dismissible_page_demo.webp
funding:
  - https://ko-fi.com/flutterman

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis:
